### PR TITLE
Split $pendingUrls and $processedUrls

### PR DESCRIPTION
**Pull request by BenMorel**
Following @AbdelkaderBah's [comment](https://github.com/spatie/crawler/pull/250#discussion_r311432548), I wanted to give a try to a split of pending URLs and processed URLs.

It does simplify, for example, `hasAlreadyBeenProcessed()`, but adds some checks in other places.

All in all it's very similar, I'm not sure which implementation looks better. @freekmurze, your choice! ;-)

### CODE REVIEW

**Comment by freekmurze** [comment]
I'll go for the new version. Thanks again! 👍

**Comment by BenMorel** [comment]
Oh, by the way, this is a BC break I'm afraid (change to protected properties); this will require a 4.7.0 release.

**Comment by BenMorel** [comment]
Actually I'm saying nonsense. This a BC break so would require a move to v5.

Maybe you should move this commit to v5-wip instead, and revert this in master?

**Comment by BenMorel** [comment]
... and this conflicts with the work already done on `v5-wip`. Oops. Should we just revert this?

**Comment by freekmurze** [comment]
Reverted, nice catch, didn't notice the BC break. Luckily I didn't tag it yet, so it's all good now.

**Comment by BenMorel** [comment]
Thanks! This won't make a difference in v5 anyway, given the changes already been done.

By the way, do you have a strategy to merge changes made to `master` into `v5-wip` since it has been branched?

Some changes will need to be merged to v5, but some of them (like the present one) will somehow conflict.

**Pull request merged**
