### PR TITLE
Support for PHP 8.0

### PR DESCRIPTION
**Pull request by pascalbaljet**
Waits for:

- [x] https://github.com/nicmart/Tree/pull/79
- [x] https://github.com/spatie/browsershot/pull/439
- [x] https://github.com/spatie/robots-txt/pull/27

### CODE REVIEW

**Comment by localheinz** [comment]
@pascalbaljet 

I will tag `nicmart/tree` in a moment!

Quick question, can everyone live with dropping support for outdated PHP version?

See Hello Freek!

Quick question, before I tag the next release of nicmart/tree: can you live with dropping outdated PHP versions, or do you need them?

See [`CHANGELOG.md`](https://github.com/nicmart/Tree/compare/0.3.0...master#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed).

**Comment by freekmurze** [comment]
@localheinz I'm pretty much always ok with dropping support for old PHP versions. 👍

**Comment by localheinz** [comment]
@pascalbaljet 

After taking a look at `composer.json` in this project, I went ahead and tagged [`nicmart/tree:0.3.1`](https://github.com/nicmart/Tree/releases/tag/0.3.1)!

Let me know if you have any issues!

🤓

**Comment by freekmurze** [comment]
@pascalbaljet After rerunning the tests, they are still failing for PHP 8. Can you take a look?

**Comment by pascalbaljet** [comment]
> @pascalbaljet After rerunning the tests, they are still failing for PHP 8. Can you take a look?

Working on it! 👍

**Comment by pascalbaljet** [comment]
Ping @freekmurze

**Comment by freekmurze** [comment]
What a beautiful PR! Thanks!

**Pull request merged**
