### PR TITLE
Improved performance when maximumDepth is enabled

### PR DESCRIPTION
**Pull request by joaomisturini**
As discussed in #208, this pull request aims to improve performance when `maximumDepth` is enabled.

Using my development computer, it was able to crawl 356 pages in a 10 minute interval. In the same time, the original version crawled 71 pages from the same website.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks for your work on this. Because you've change the signature of a public method, this is a breaking change.

I'll decide later this week if the benefits of this change warrant a new major version of the package.

**Comment by freekmurze** [comment]
> Using my development computer, it was able to crawl 356 pages in a 10 minute interval. In the same time, the original version crawled 71 pages from the same website.

Have you performed this test multiple times? Because the performance increases could also be attributed to better network conditions.

**Comment by joaomisturini** [comment]
I have done it 2 times, only, but I don't remember the result numbers and I don't have access to my computer right now.

I will run it 3 times again tonight, and post the results here.

**Comment by joaomisturini** [comment]
Finally did the tests! Sorry it took so long.

I did 3 tests using my branch (depth-performance) and 3 others using the master branch. As you said, network conditions ended up affecting performance, but the difference is too big to be just a network condition. The results are:
* 327, 329 and 335 pages using depth-performance branch;
* 71, 71 and 72 pages using master branch.

I ran the tests using PHP 7.2, on Docker containers. The host OS is Ubuntu 18.04. My internet connection has 20 Mbps for download and 5 Mbps for upload.

The crawler was configured with maximumDepth = 2 and concurrency = 1. The observer was just a simple class that logs the crawled pages to a log file.

The website crawled was https://g1.globo.com/, a popular news website here in Brazil.

I am keeping the log files for a while, and I can make a gist of it if needed.

Again, sorry for the delay. Some college papers got in the way this week.

**Comment by freekmurze** [comment]
> Finally did the tests! Sorry it took so long.

No worries, there are no deadlines for contributors! Thanks for you work on this!

**Comment by freekmurze** [comment]
Can you rebase this against the current master?

**Comment by joaomisturini** [comment]
I just rebased this branch, and solved the conflicts.

**Comment by freekmurze** [comment]
I've decided to not pull this in for now, but when we create a new major version of the crawler. That'll probably happen when PHP 7.4 is released.

**Pull request closed without merging**
