### PR TITLE
[v5] Get rid of CrawlUrl::$id

### PR DESCRIPTION
**Pull request by BenMorel**
Guzzle's Pool allows string keys, allowing us to use the URL as the key, and avoiding the need for a numeric ID in `CrawlUrl`.

*This PR targets `master` for now, but I think the project should be branched to `v5` and this PR retargeted.*

### CODE REVIEW

**Comment by BenMorel** [comment]
Note that while I removed `CrawlQueue::getUrlById()`, I had to add a `get()` method to get the `CrawlUrl` object back from the stringified URL, as Guzzle accepts strings but not objects as keys:

https://github.com/spatie/crawler/blob/6fed8417f0f9489c7a391ffa0cc1460778cc351e/src/CrawlQueue/CrawlQueue.php#L15

I hope to be able to further simplify the code by adding support for object keys in the Guzzle's `Pool` at some point. I opened an issue with Guzzle, this should be fairly easy to do, provided that it can be done in a BC manner:

https://github.com/guzzle/guzzle/issues/2322

**Comment by freekmurze** [comment]
I've created a `v5-wip` branch and retargeted the PR.

**Comment by brendt** [comment]
Looks great, thanks Ben!

**Comment by BenMorel** [comment]
Thank you, I'll soon move forward with another PR!

**Pull request merged**
