### PR TITLE
WIP: add new observer method that is called when a link is found *again*

### PR DESCRIPTION
**Pull request by bobemoe**
I have found I needed to add this to allow my `CrawlObserver` to count the number of times a link is found, and also collate all the `foundOnUrl`'s for the given link.

I can now report *all* pages that link to a specific 404 rather than just the first one it was found on.

If this was already possible please let me know, I couldn't find another way :)

I can add tests and docs if you'd be interested in merging?

I guess adding new abstract function would break BC on all existing observer implementations, this would need to be major release?

### CODE REVIEW

**Comment by Redominus** [comment]
You could implement a new queue that counts how many times am Url has been found.

**Comment by bobemoe** [comment]
I did consider that, I think I would have to use `CrawlQueue::has` as the logic that checks if it is already queued is in `Crawler::addToCrawlQueue`, the issue with this is that the `foundOnUrl` is not passed in, so although I could count, I wouldn't be able to collate the `foundOnUrl`'s.

**Comment by bobemoe** [comment]
I am still using this as a patch in https://git.jhodges.co.uk/jhodges/sitemap and have still found no other way to achieve this otherwise.

**Comment by bobemoe** [comment]
Not sure how I reopen this as suggested by spatie-bot?

**Pull request closed without merging**
