### PR TITLE
Implement CrawlProfile interface for internal links

### PR DESCRIPTION
**Pull request by ilazaridis**
This is related to https://github.com/spatie/http-status-check/issues/22

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you add a test to prove that this works?

**Comment by ilazaridis** [comment]
When I try to run existing tests adding an external link too, crawler seems to ignore this link, so I didn't go any further with tests. Is that intentional ? I didn't have time to look into it yet.

**Comment by ilazaridis** [comment]
Argh, find it! Missing trailing slash from the testing url led me to wrong conclusions. I 've fixed that and added a proper test.

**Comment by freekmurze** [comment]
Great PR, thanks!

**Pull request merged**
